### ISSUE TITLE
大佬，咨询2个问题

### ISSUE THREAD

**Issue by weiyakeji** [techprober/mosdns-lxc-deploy#10]
问题1，如何再调用远程dns查询时附带上ecs信息，v4是可以的，v5版官方就写了一句话，有点懵，大佬能否加上。
远程查询附带上ecs能缓解查询乱跳的问题，应该有不少代理用的负载均衡的方式，请求被随机分散到指定的几条线路上。

问题2，能否增加一个ddns域名跳过缓存，有动态公网IP的宽带一般都会用ddns来对外开放一些服务，在本地也可以直接用ddns的域名来访问内网服务，因为是动态公网IP，经常会变，不适合进缓存。

**Comment by piyoki** [comment]
@weiyakeji 這些 問題 你應該轉移到 mosdns 的官方 repo 提問，傳送門：https://github.com/IrineSistiana/mosdns/releases
